### ISSUE TITLE
Problems with neural calibaration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RoboCup-SSL/ssl-vision#20] opened 2015-06-03 19:00 UTC
```
What steps will reproduce the problem?
1. Click 'neural calibration' tab on the right
2. Choose some colour. Click on some example points of that colour on the 
camera image.
3. Click on 'train neural network' and then click on 'loal neural to LUT'

What is the expected output? What do you see instead?
The ssl vision aborts.


What version of the product are you using? On what operating system?
Ubuntu 10.04

Please provide any additional information below.
Following is what is displayed at the terminal window when ssl-vision aborts.

OpenCV Error: Image step is wrong () in cvSetData, file 
/build/buildd/opencv-2.1.0/src/cxcore/cxarray.cpp, line 902
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.1.0/src/cxcore/cxarray.cpp:902: error: (-13)  in function cvSetData

Aborted




```

Original issue reported on code.google.com by `nehch...@gmail.com` on 23 May 2012 at 12:08

**Comment by AlexanderDanzer** [comment] 2017-01-29 14:20
I also have problems using the neural network calibration.
Can anyone give an explanation how a successful calibration procedure might look like?
I am able to capture samples and training the network seems to do something. How to do I apply the calibration? "Load to LUT" does not seem to have any effect for me.

**Comment by g3force** [comment] 2017-01-29 19:03
Yes, the disadvantage of this plugin is, that you have to calibrate all colors. The neural network will fill the full LUT table. So if you skip a color, the result of the remaining colors will be worse because they have to cover more pixels.
You can use the plugin for an initial calibration, though.

**Comment by asctec-andre** [comment] 2017-01-29 19:13
Anyway, the problem initially reported could not be reproduced. The plugin works and SSL vision does not crash. I think we can close this issue.

**Closed** 2017-12-16 11:18 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
